data:
  batch_size: 1
  data_pattern: CF_sample0.npy
  seismic_data_dir: dataset/OpenFWI_Ablation/Seismic_Data/
  velocity_data_dir: dataset/OpenFWI_Ablation/Velocity_Data/
diffusion:
  image_size: 72
  model_path: pretrained_models/model-4.pt
  objective: pred_noise
  sampling_timesteps: 250
  timesteps: 1000
experiment:
  log_interval: 10
  name: ablation_baseline_no_tricks_dt30_ts10
  random_seed: 8888
  results_dir: ablation_results/
  save_intermediate: false
  save_metrics: true
model:
  channels: 1
  dim: 64
  dim_mults:
  - 1
  - 2
  - 4
  - 8
  flash_attn: false
optimization:
  diffusion_ts: 30
  grad_clip: 1.0
  grad_norm: false
  grad_smooth: null
  initial_type: smoothed
  lr: 0.01
  missing_number: 0
  model_blur: false
  noise_std: 0.0
  noise_type: gaussian
  patch_kernel_size: null
  patch_stride: null
  sigma: 10.0
  ts: 10
  use_patches: false
pde:
  dt: 0.001
  dx: 10.0
  f: 15.0
  gz: 10
  n_grid: 70
  nbc: 120
  ng: 70
  ns: 5
  nt: 1000
  sz: 10
