data:
  batch_size: 1
  data_pattern: '*.npy'
  seismic_data_dir: example/example_dataset/example_marmousi/Seismic_Data/
  use_mmap: true
  velocity_data_dir: example/example_dataset/example_marmousi/Velocity_Data/
diffusion:
  image_size: 72
  model_path: pretrained_models/model-4.pt
  objective: pred_noise
  sampling_timesteps: 250
  timesteps: 1000
experiment:
  log_interval: 10
  name: marmousi_red_diffeq
  random_seed: 8888
  results_dir: example/example_result/marmousi/
  save_intermediate: false
  save_metrics: true
model:
  channels: 1
  dim: 64
  dim_mults:
  - 1
  - 2
  - 4
  - 8
  flash_attn: false
optimization:
  initial_type: smoothed
  lr: 0.03
  missing_number: 0
  noise_std: 0.0
  noise_type: gaussian
  reg_lambda: 0.75
  regularization: diffusion
  sigma: 20.0
  sigma_x0: 0.0001
  ts: 300
  use_time_weight: false
pde:
  dt: 0.001
  dx: 10.0
  f: 15.0
  gz: 10
  n_grid: 190
  nbc: 120
  ng: 190
  ns: 5
  nt: 1000
  sz: 10
